### PR TITLE
added open in new tab setting for timeline entity links

### PR DESCRIPTION
**Pull request by jordanmills**
I think I found an easy way to get a simple yes/no setting for opening in a new tab (which should default to the current behavior).  I'm still working on toolchain setup for typescript so this is not tested well.  Feel free to deny and tell me to learn ts/obsidian more - this is WAY on the other side from the programming I'm used to.

### CODE REVIEW

**Comment by clairefro** [comment]
Thanks for taking initiative! When I tried this, it is always opening the link in the active tab, regardless of the setting. 

Instead of making this a setting option, would it make more sense to toggle open in tab on/off by holding a key on the keyboard?

**Comment by clairefro** [comment]
Again, thank you for taking the time to add this! In the end I went with click conventions and updated behavior in [1.1.1](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.1.1)

**Comment by jordanmills** [comment]
I might have missed something in the getLeaf behavior that I needed to learn better then.  I really appreciate you taking the time to look at it.  It's my first attempt to do anything for obsidian so I was not expecting much of it.  And thank you for implementing the FR!

**Comment by clairefro** [comment]
should you choose to continue your journey in Obsidian plugins, check out the hot-reloader plugin! 

https://github.com/pjeby/hot-reload

It automatically refreshes your plugin every time you make changes in your code.  A must-have for plugin dev

**Pull request closed without merging**
