### PR TITLE
Feat/order by

### PR DESCRIPTION
**Pull request by Guillaume-de-Maleprade**
Added orderby feature (using a new 'flag' item syntax, for potential future options).
This allows a user to add a specific ordering at timeline level

### CODE REVIEW

**Comment by clairefro** [comment]
WOW! I've been playing around with this this morning and it's an amazing quality of life improvement. Thank you so much for taking the time to add this (and documentation!). The syntax is beautiful. 

A few notes 
1. can we parse the flag to allow for and trim spaces? (`> ORDERBY style|start` and `> ORDERBY style | start`)
2. Regarding `style`: Right now the only style users have access to modifying is `color` - perhaps `color` could be the sort property instead? I couldn't get items to order by style (color) with the style option

````markdown
```
# I expect colors to the grouped together in the stack
> ORDERBY style|start
 
- [2026~2028] Baaaaaaz 
- [2024~2028] Fooooooooo 
- [2025~2030] #red Barrrrrr 
- [2020~2030] #red Zoooooooo 
```
````
image

 
3. Lastly, I'd like to add this to the "Cheatsheets" (cheatsheet.md linked in README, and the cheatsheet text in the Settings tab)  for users to play with, perhaps with a more concise example. If you don't add this, I will! 


Basic example I played with: 
````markdown
```chronos
> ORDERBY content
 
- [2026] Baaaaaaz 
- [2024] Fooooooooo 
- [2025] Barrrrrr 
```
````

image

````markdown
```chronos
> ORDERBY -content
 
- [2026] Baaaaaaz 
- [2024] Fooooooooo 
- [2025] Barrrrrr 
```
````
image

Or something like this

Again, thank you

**Comment by Guillaume-de-Maleprade** [comment]
There was an issue when color or description was empty. 
This fix and the other remarks have been implemented in the latest commits 😄

**Comment by Guillaume-de-Maleprade** [comment]
And by the way, the ordering is orders-of-magnitude faster if there are empty groups `{ }` instead of no groups at all

**Comment by clairefro** [comment]
> ordering is orders-of-magnitude faster if there are empty groups { } instead of no groups at all

Interesting! I'll play with this and see if it makes sense to give all items an empty group by default.

Sorry I'm slow to respond, still on boarding to a new job and mainly have time for this on weekends

**Comment by Guillaume-de-Maleprade** [comment]
No worries, I won't be available for almost 3 weeks anyways

**Comment by clairefro** [comment]
Works great! merging this to main for now and will make some edits like taking out moment before release

Thanks for contributing this valuable feature 🙏🏼

**Comment by Guillaume-de-Maleprade** [comment]
I'm happy I could do something hopefully useful  😁

**Comment by clairefro** [comment]
added in `1.0.8` release

**Pull request merged**
